### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by okaka-c** [okaka-c/goodlifterlog#115]
お世話になっております。
MVPリリースのレビュー依頼を提出いたします。
よろしくお願い致します。

## 各種情報
- サービス名
  PowerLifter's Log
- サービスURL
  
URLと、サービス名が違いますがドメイン取得をしてURLとサービス名を一致させます。

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] #120
- [x] ログイン・ログアウト機能
- [x] プロフィール登録機能(会員登録時に同時におこなう)
- [x] プロフィール編集機能
- [x] 大会情報の記録機能
    - 大会名
    - 場所（施設名）
    - 開催日
    - 大会種別(公式大会または非公式大会)
    - ギア種別(ノーギアまたはフルギア）
    - 競技種別(パワーリフティング、シングルベンチか)
    - 年齢別区分(一般、サブジュニア、ジュニア、など年齢カテゴリ)
    - 体重別区分(47kg級、52kg級など）
- [x] 試技結果の記録機能   
    - 検量体重
    - スクワット 挙上重量、判定結果
    - ベンチプレス 挙上重量、判定結果
    - デッドリフト 挙上重量、判定結果
    - 反省点コメント
- [x] 大会情報の編集・削除
- [x] 試技結果の編集・削除
- [x] 大会結果一覧表示
- [x] 大会結果詳細表示(大会情報と試技結果詳細表示

## READMEレビュー時から変更した機能
- 試技結果記録機能について以下の通り機能を減らしました。
3種目(スクワット、ベンチプレス、デッドリフト)の合計挙上重量計算を
MVPリリースには含めず本リリースに含めることにしました。

- パスワードリセット機能を減らしました。
MVPリリースの期限に間に合わないため、減らしました。本リリースまでに実装をします。

## 本リリース時に実装したい機能
- レスポンシブ対応
- お問い合わせ、利用規約、プライバシーポリシーの作成
- パスワードリセット機能
- 大会情報記録と試技結果記録をステップ入力・確認画面を用いてできるようにする
- フラッシュメッセージ
- 会場の施設名入力時の手間を減らす。(GoogleのAPI による自動入力機能使用)
- 3種目(スクワット、ベンチプレス、デッドリフト)の合計挙上重量計算して表示
- 過去の出場した大会からの伸び率を計算して表示
- 成績のグラフ化
- 持参する持ち物・食べ物リスト作成・管理機能
- 出場予定の大会を登録機能
- 持ち物・食べ物リストを大会予定に紐づけて登録
- LINE通知機能
  - 出場予定の大会を日付付きで登録
  - 大会が近づくと持ち物・食べ物リストに買いてあるものを準備するように促す通知
  - 大会が終わったら「試技結果を記録しましょう」とユーザーに促す通知
- SNSシェア用の文章を作成（X用、インスタ用を想定）

### レスポンシブ非対応です。スマホサイズに対応しています。

-  トップページ(未ログインユーザーのトップ)
[![Image from Gyazo](https://i.gyazo.com/0b0cc931771d9935cce9b57ea9ce98e7.png)](https://gyazo.com/0b0cc931771d9935cce9b57ea9ce98e7)
-  ログインページ
[![Image from Gyazo](https://i.gyazo.com/c5069897ad47a7cd2dba57d4dd828ef8.png)](https://gyazo.com/c5069897ad47a7cd2dba57d4dd828ef8)
-  新規会員登録ページ
[![Image from Gyazo](https://i.gyazo.com/d1f9d9900cb148f8e74f534cc6776088.png)](https://gyazo.com/d1f9d9900cb148f8e74f534cc6776088)
-  大会結果一覧ページ(ログイン後トップ)
[![Image from Gyazo](https://i.gyazo.com/6741729d7a854250e77f9141dc046763.png)](https://gyazo.com/6741729d7a854250e77f9141dc046763)
-  プロフィールページ
大会結果一覧ページのヘッダーの人型アイコンより飛べます
[![Image from Gyazo](https://i.gyazo.com/54f61784509fe6861684c3fb2297b4ba.png)](https://gyazo.com/54f61784509fe6861684c3fb2297b4ba)
-  プロフィール編集ページ
[![Image from Gyazo](https://i.gyazo.com/af16736899a3dd0d928a878a0b9b5c27.png)](https://gyazo.com/af16736899a3dd0d928a878a0b9b5c27)
-  大会情報登録ページ
ボトムナビゲーションの「記録するボタン」から飛べます
[![Image from Gyazo](https://i.gyazo.com/b34981c39f4f6dfb997ebcfb02cb3989.png)](https://gyazo.com/b34981c39f4f6dfb997ebcfb02cb3989)
-  大会情報詳細ページ
大会結果一覧ページの詳細ボタンから飛べます。
試技結果はこのページの「大会結果記録」ボタンから登録できるようになっています。
[![Image from Gyazo](https://i.gyazo.com/73f5e9502036fd9a74d5cb7e5b0d9943.png)](https://gyazo.com/73f5e9502036fd9a74d5cb7e5b0d9943)
-  試技結果登録ページ
[![Image from Gyazo](https://i.gyazo.com/78b1852ad847831b0057cd0e380a141b.png)](https://gyazo.com/78b1852ad847831b0057cd0e380a141b)
- 試技結果詳細
大会情報詳細ページにて、大会情報の下に表示されます。
[![Image from Gyazo](https://i.gyazo.com/178e4c9a9936be18a22a7390cce9e83d.png)](https://gyazo.com/178e4c9a9936be18a22a7390cce9e83d)
[![Image from Gyazo](https://i.gyazo.com/1a4dec99a7ed8c555124676a9e93421e.png)](https://gyazo.com/1a4dec99a7ed8c555124676a9e93421e)
- 大会情報編集ページ
[![Image from Gyazo](https://i.gyazo.com/b7e061c11cead9128912a7a2419aa17b.png)](https://gyazo.com/b7e061c11cead9128912a7a2419aa17b)
- 試技結果編集ページ
[![Image from Gyazo](https://i.gyazo.com/f6b8fe94ce4c15059d5cf4aa40f9bd5c.png)](https://gyazo.com/f6b8fe94ce4c15059d5cf4aa40f9bd5c)

以上、ご確認のほどよろしくお願い致します。

**Comment by kenchasonakai** [comment]
LGTMです 💪

**Comment by okaka-c** [comment]
ありがとうございます！
クローズ致します。
