### ISSUE TITLE
Issueベースの開発レビュー依頼

### ISSUE THREAD

**Issue by okaka-c** [okaka-c/goodlifterlog#32]

**Comment by okaka-c** [comment]
## 概要

### 実装予定の機能
#### MVPリリース時

- [ ] 会員登録機能
- [ ] ログイン機能
- [ ] プロフィール機能
- [ ] 大会結果一覧表示
- [ ]  大会結果記録機能
- [ ]  大会結果の編集・削除
- [ ] 大会結果詳細表示

#### 本リリース時

- [ ] SNSシェア機能
- [ ]  持参する持ち物・食べ物リスト作成・管理機能
- [ ]  成績のグラフ化
- [ ] 出場予定の大会を登録機能
- [ ] LINE通知機能

### 必要なページ

#### MVPリリース時
- [ ] トップページ
- [ ] ログインページ
- [ ] 新規会員登録ページ
- [ ] プロフィールページ
- [ ] プロフィール編集ページ
- [ ] パスワードリセット申請ページ
- [ ] パスワード更新ページ
- [ ] 大会結果一覧ページ
- [ ] 大会結果詳細ページ
- [ ] 大会情報・大会結果登録ページ
- [ ] 大会情報・大会結果編集ページ

#### 本リリース時
- [ ] 出場予定大会登録ページ
- [ ] 成績グラフ化ページ
- [ ] テンプレート作成ページ
- [ ] 持ち物リスト作成ページ

**Comment by Tsuchiya2** [comment]
Projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認いただき、上記が確認できる状態でご提出をお願いいたします。

<img width="475" alt="image" src="https://github.com/okaka-c/goodlifterlog/assets/61481161/a07c27a5-5176-430a-b44b-0b2d7ccfbae1">

**Comment by okaka-c** [comment]
申し訳ございません。
リポジトリのProjectsに看板・issue・ストーリーポイントが
確認できるように設定致しました。
再度、提出致します。
ご確認の程、よろしくお願い致します。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

**Comment by okaka-c** [comment]
レビュー頂き、ありがとうございます。
